### ISSUE TITLE
Check if connection to DB works in install script

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#100]
Check if connection to DB works in install script

**Comment by kyleobrien91** [comment]
Just to flesh out a bit more

Running ```php artisan asgard:install``` and using DB details that don't work results in output similar to
```
Database successfully configured

  User Module
  Starting the User Module setup...

SQLSTATE[HY000] [2002] Operation timed out
```

Iterative workflow is then to change DB settings and try install again. Unfortunately, that results in the following:

```
Welcome!
  Starting the installation process...

Asgard has already been installed. You can already log into your administration.
``` 

Obviously we know it probably isn't setup fully since we couldn't advance past the database connectivity point. 

@nWidart - happy to look at this. Will you point me to the install handler? I'll have a look at updating this.

**Comment by kyleobrien91** [comment]
@nWidart - nvm. Found the file. Will try and submit a PR soon.

**Comment by nWidart** [comment]
Hello, 

You can run the installation command with the `--force` flag to avoid that 'already installed' notification.

**Comment by kyleobrien91** [comment]
@nWidart - yeah. Also just deleted the .env file and ran the command normally. Would still be nice to check connection anyway.

**Comment by GinoPane** [comment]
Yep, faced the same issue and wanted to report:)

**Comment by joshbrw** [comment]
Resolved in https://github.com/AsgardCms/Core/commit/09ab55cb3455227c8db4b77ff418b5f39d2c1d8e
