### ISSUE TITLE
Installation on domain subfolder 

### ISSUE THREAD

**Issue by vizo** [AsgardCms/Platform#105]
There is no base href set in templateas and assest have absolute path to root.

So i guess there is no way to install it under domain.com/subfolder ?

__UPDATE__:
I made a pull request https://github.com/AsgardCms/AdminLTE/pull/10.

**Comment by tk-s** [comment]
i just put my comment here too:

If i remeber it right, all i had to do to have a working subfolder-installation (of AsgardCMS) was adding
RewriteBase /folder/
to your .htaccess in public.
There was an issue with stylist, which should be fixed now (floatingpointsoftware/stylist#17)

**Comment by vizo** [comment]
With RewriteBase /folder/ it can't work because urls are absolute. Check out my pull request https://github.com/AsgardCms/AdminLTE/pull/10.

**Comment by tk-s** [comment]
yes, i’ve seen that, thanks for pointing out.
Since it is working here, that mabe because my changes to stylist have not made it yet into a release (i applied them manually i guess).

As far as i understand your PR, they are only working for the backend, not for the frontend themes (where the same problem occurs?)

Am 06.09.2015 um 16:09 schrieb vizo <notifications@github.com<mailto:notifications@github.com>>:


With RewriteBase /folder/ it can't work because urls are absolute. Check out my pull request AsgardCms/AdminLTE#10<https://github.com/AsgardCms/AdminLTE/pull/10>.

**Comment by vizo** [comment]
As i remember, there was the same problem. I already uninstalled it because i needed working CMS for my project with deadline 3 weeks.

**Comment by tk-s** [comment]
Then this Issue is fixed as soon as the last version of stylist is installed along asgard (at least it is working here without problems)

There are thou some other minor places, where the root-path is hardcoded. (see my PR for MediaModule as example)

Am 06.09.2015 um 16:26 schrieb vizo <notifications@github.com<mailto:notifications@github.com>>:


As i remember, there was the same problem. I already uninstalled it because i needed working CMS for my project with deadline 3 weeks.

**Comment by nWidart** [comment]
I'll close this since stylist was updated a while ago to allow this. :smile:
