### ISSUE TITLE
Add an manual image crop

### ISSUE THREAD

**Issue by nWidart** [AsgardCms/Platform#14]
Add a manual image crop functionality, using http://fengyuanchen.github.io/cropper/. 

This will be done after the image is uploaded, meaning after the main thumbnails have been created.

**Comment by motchju** [comment]
Hello,

I did some work with the cropper.

http://labo.mugdesign.be/crop/demo/index.html

How do you see the workflow ?

I have in mind:

You set a Thumbnails and you add a flag '**manualcrop**' (same as Image quality)

> $this->app[ThumbnailManager::class]->registerThumbnail('cropImage', [
    'manualcrop' => [ 'width' => 200, 'height' => 300 ],
    'crop' => [
        'width' => 200,
        'height' => 300
    ],
]);`

By default, the image will be created with what you have define in the crop.

Via the media, if the flag manualcrop is present, you may open the original image, and you can crop it yourself, the width and the height of the crop area will use the value define in the manualcrop.

Once your manipulation is over, we override the current image. One api need to be created for it.

Keep in mind:

It will be nice to create an exception , for the **php artisan asgard:media:refresh**, in order to skip the thumbnails set manually, we don't want to erase it, if so maybe create a force flag.

We may have multiple storage :  local / Amazon S3, ...

Access-Control-Allow-Origin : https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS (**only if you don't use local storage**)

**Comment by nWidart** [comment]
The basic idea was to have a link on the image edit view "crop manually" or something. That would bring the user to a page with the cropper UI (from your example). 
Which gives the user the ability to create a new cropped version of the image, after giving it a name.
That name would be used to fetch that image again (just like usual thumbnails).

**Comment by motchju** [comment]
By manually, you mean also set the width and height ? I think it's better to have a fix size set by default. 

For instance, in my current project I have more than 3000 images, the render with the default setting is fine for 95 % of them, only a few need to be set manually.  

Anyway if you have time we can still discuss about it and I will help you with the cropper if needed

**Comment by motchju** [comment]
I did some test, and it's working well (croper via the admin, api to send the blob, ...)

About the way you see it, don't you think it's better to have the normal behavior : update the image, let the CMS do the creation of the others thumbnails and only after using the crop ?

Sorry to bother you about it, but in my case for instance I upload a 1200 * 900 image and I need 4 versions of it.
- V1: 1000 * null
- V2: 600 * null
- V3: 400 * null
- V4: 800 * 800 

And only for V4 I need to crop it manually with fix size: 800*800. 

If needed  I'm available via Slack to discuss about it.
