### ISSUE TITLE
Laravel Authorization and User module

### ISSUE THREAD

**Issue by imajus** [AsgardCms/Platform#169]
I've tried to use Laravel 5 Gates (Illuminate\Auth\Access\Gate) in order to authorize access to some methods accessible via frontent and found out that Laravel Auth is not the same as Asgard's. For some reason $this->auth->user()->id provides current user ID and Auth::id() doesn't. I guess for the same exact reason Gates don't work.
Is there a way I can setup User module to work with Laravel Authorization system? 
Just in case, this is how I want to use authorization: https://laravel.com/docs/5.1/authorization#defining-abilities

**Comment by nWidart** [comment]
If you want to use laravel's authentication, you need to create that implementation https://asgardcms.com/docs/user-module/drivers#implementing-custom-providers

The `Auth::` facade will regardless not work in AsgardCms because Asgard does not ty itsef to a particular authentication method. It can use Sentry / Sentinel / Lock / Whatever you want.
