### ISSUE TITLE
General error: 1215 Cannot add foreign key constraint

### ISSUE THREAD

**Issue by divspace** [AsgardCms/Platform#188]
I'm getting the following error when I start a new project:

    [Illuminate\Database\QueryException]
    SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `dashboard__widgets` add constraint dashboard__widgets_user_id_foreign foreign key (`user_id`) references `users` (`id`) on delete cascade)

    [PDOException]
    SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

The issue is with this file:

`Modules/Dashboard/Database/Migrations/2015_04_02_184200_create_widgets_table.php`

On line 21:

`$table->foreign('user_id')->references('id')->on(config('auth.table', 'users'))->onDelete('cascade');`

See the attached screenshot as well:

![untitled-1 fw](https://cloud.githubusercontent.com/assets/10470082/14408071/09126202-fe9a-11e5-8863-b5ee972fda0a.png)

**Comment by mikemand** [comment]
This error means that the auth table (by default `users`) does not exist. You need to run `php artisan asgard:install` before doing anything else.

**Comment by tagmeo** [comment]
This happens automatically though after Composer is done running. Even if you run the installer manually or the forced migrate module it still fails.

**Comment by hannesbe** [comment]
Having the same problem on Homestead/Vagrant. It looks to me the Composer installation is currently not working for any fresh install. 

`composer.json` includes some `post-install-cmd` scripts and `php artisan module:publish` triggers `php artisan module:migrate --force`, resulting in the module migrations being run before the platform migration.

This also causes when not having the default `forge` database with user `forge `user & blank password on localhost to get a database connection error at this point. 

If you did have or created this database & user and tried again (as I did), it tries to add a foreign key to the `users` table before it has been created ( `migration` & `dashboard__widgets` are the only tables present at this point), causing this error.

You can work around it like this: 

- Remove tables `migration` & `dashboard__widgets` from the database, so you have an empty database.
- Run `php artisan asgard:install` (only now you can set the database settings using the wizard)
- I'm not sure if this is needed, maybe the install finishes this, but I also ran `php artisan module:publish` again because it was interrupted by this error.

**Comment by mikemand** [comment]
Ahh, ok. I know what the problem is. Composer's behavior changed: https://github.com/composer/composer/issues/5066#issuecomment-196979820

It doesn't run `post-install-cmd` anymore if there is no `composer.lock`, but instead runs `post-update-cmd`. How unsettling...If you run `composer install` (or in this case, `create-project`) you should expect it to run any `install` scripts, and not `update` scripts...

**Comment by divspace** [comment]
If you run the following:

`composer create-project asgardcms/platform PROJECT-NAME`

It will fail as well:

	Writing lock file
	Generating autoload files
	> php artisan clear-compiled
	> php artisan stylist:publish
	AdminLTE assets published.
	Flatly assets published.
	Assets published.
	> php artisan module:publish
	Published: Core
	Published: Dashboard
	Published: Media
	Published: Menu
	Published: Page
	Published: Setting
	Published: Translation
	Published: User
	Published: Workshop
	> php artisan module:migrate --force
	Running for module: core
    
     [PDOException]
    SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)
    
    Script php artisan module:migrate --force handling the post-update-cmd event returned with an error

So it's running the `post-update-cmd' instead of the `post-install-cmd`, and since there's no `.env` file setup, it fails. If you create one and run it again, it fails.

**Comment by nWidart** [comment]
Hello,

thank you for reporting the issue. This is indeed related to a changed behaviour in Composer.

User **hannesbe** suggested the following work around:

- Remove tables `migration` & `dashboard__widgets` from the database, so you have an empty database.
- Run `php artisan asgard:install` (only now you can set the database settings using the wizard)
- I'm not sure if this is still needed, but I also ran `php artisan module:migrate --force` again because it was interrupted by this error, returns nothing to migrate on all modules though.

This is until I decide on what to do, most likely remove the post-update-commands in composer.json.

**Comment by nWidart** [comment]
I removed the migrate command from the post update command, which fixes the create-project new behaviour.

https://github.com/AsgardCms/Platform/releases/tag/1.14.1

Thank you for reporting the issue!
