### ISSUE TITLE
on github this shows up as being a javascript package

### ISSUE THREAD

**Issue by vesper8** [AsgardCms/Platform#280]
pretty sure it should be in php since it's built on laravel

**Comment by nWidart** [comment]
True, if you know how let me know. 😄

**Comment by becquerel** [comment]
Github determines this by scanning the code, and it found out, that this package is almost 50% JavaScript (1481 files), while there is only little over 19% PHP (91). It is because of the included published vendor JS libraries inside `public/modules`, ... unfortunately as long as they are present in the repository, I don't think there is a way to change it
https://github.com/AsgardCms/Platform/search?l=JavaScript

Option would be to remove JS vendors, and install them during asgard installation using bower or NPM (I believe they are published during installation anyway, aren't they ?)

**Comment by nWidart** [comment]
Laravel had the same issue and they found a way to fix it. Not sure how though.
