### ISSUE TITLE
Why use Array cache store system? Can i replace it with something?

### ISSUE THREAD

**Issue by arturmamedov** [AsgardCms/Platform#324]
The array cache not save data for next requests but work only for one request lifecycle.
I understand that it needed for tags() tagged cache. 

And my question is: if we can replace this store system with something else that mantain the data trough all requests.

Thanks!

**Comment by nWidart** [comment]
Hello,

Array is used by default, because as you mentioned it's not a real cache. In development we usually don't want that. 
However, in production/staging environments, of course, you should switch to another driver, like redis or memcached.

You might wonder why array and not file, simple reason is Asgard leverages cache tags, which isn't supported by the file driver.
