### ISSUE TITLE
ErrorException - Undefined offset: 1

### ISSUE THREAD

**Issue by BakuDev** [AsgardCms/Platform#343]
### Summary of issue

Recorded a video of the issue: https://www.useloom.com/share/9bb78b4c914840c5b97ec163534fd1de

### Steps to reproduce

Add some extra language, open Settings page, press Save

### System Details

- Operating System

Windows

- PHP Version
7.1-x64

- Laravel Version

5.4

- `Asgardcms/Platform` version

Latest

**Comment by nWidart** [comment]
Hello,

Thanks for the video.

I can't reproduce this locally, after adding new languages or other options. This is the line failing for you: https://github.com/AsgardCms/Platform/blob/2.0/Modules/Setting/Repositories/Eloquent/EloquentSettingRepository.php#L219
Can you run `dd($settingName)` just before that line  to see which setting is failing?

It basically means it found a setting that doesn't have a `::` in its name.

**Comment by nWidart** [comment]
you could also var_dump it, to avoid the script from stopping.

**Comment by darron1217** [comment]
@nWidart 
I'm currently facing the same problem...
![image](https://user-images.githubusercontent.com/8064923/34815206-e1921d2c-f6f3-11e7-9003-49d87bd6635f.png)

I think this caused by the code `$this->setting->createOrUpdate($request->all());`
Which includes `q=/path/to/route` parameter in querystring.
https://github.com/AsgardCms/Platform/blob/ca13b958b0240bf5f004390d4628863aa6c20137/Modules/Setting/Http/Controllers/Admin/SettingController.php#L44

So we need to change the line into `$this->setting->createOrUpdate($request->request->all());`
(According to this answer https://stackoverflow.com/a/27367330)

P.S. I've tested it!
