### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by fer-ri** [AsgardCms/Platform#36]
Hi

i try to run `php artisan asgard:install` but give me error

```
 [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'asgardcms.settin
  g__settings' doesn't exist (SQL: select * from `setting__settings` where `n
  ame` = core::locales limit 1)






  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'asgardcms.settin
  g__settings' doesn't exist
```

any idea?

try to run `php artisan migrate` and `php artisan module:migrate` but still no luck

Thanks

**Comment by RadoslavAngelov** [comment]
Hi,

what if I clone already existing project to which I have to develop another functionality, I have to put .env file manually I guess but I get the same error.

This are the steps that I`ve made:
1. clone repo
2. run composer install
3. put .env file
3. run php artisan migrate

**Comment by nWidart** [comment]
You can probably read #83 about adding asgard to existing projects.

**Comment by RadoslavAngelov** [comment]
I don`t want to add asgard to an existing project. My co-worker started developing application using AsgardCMS, and since we have to cooperate I have to clone his repo and to add some features but I can`t even start the project. I think it is because my database is not migrated and that is because I`ve tried with php artisan migrate but it didn`t help.
