### ISSUE TITLE
Localization redirect on submitting login form

### ISSUE THREAD

**Issue by lastmaher** [AsgardCms/Platform#429]
Hello, 
I have installed a fresh copy of Asgardcms, and everything is well.
But when I try to login it redirects and not submit the login credentials.
I tried to dd($credentials) in AuthController but it seems that the redirection occur before getting the the controller!
Fresh copy available here http://gne.pearlzonesa.com
Anyone have an idea ?

**Comment by kefahnaj** [comment]
same issue and could not understand why

**Comment by nWidart** [comment]
Hello,

This is usually an issue with mamp, where cookies aren't written.
However, it looks like you managed to reproduce this on a server.

I don't know why, but something with the server makes it not write cookies, just as with mamp.

Feel free to let us know if you find something.

**Comment by kefahnaj** [comment]
same issue , it work on local host but not on web and all requirements are setting up , any idea what could cause that . i use VPS server ..

**Comment by kefahnaj** [comment]
i think the issue is in asgard version 3 , cause i tried fresh copy of version 2 with the same domain and server it works perfect , then i re tried version 3 , it is not work , and makes same issue  . 
i think something on version 3 stop writing cookies by default , and make it depend on server setting ..

**Comment by nWidart** [comment]
Yeah I've figured that too, but wasn't able to pinpoint what exactly would be causing this.

**Comment by kefahnaj** [comment]
hope you will find where , i tried V3 on other server and it works , so i hope to find where , any way thank you

**Comment by kefahnaj** [comment]
i created v2 fresh app .. then i copied all files inside config directory (without asgard directory) to my V3 app , and now it works fine , i will detect what file is making that issue  after but now it is work and server respond to write cookies very well .
i think (filesystem.php or laravellocalization.php ) .. if some one detect that file  please inform just to understand how it works .

**Comment by aalssamani** [comment]
If you are using MAMP cookies aren't written.. so 

On my Mac (MAMP), the path is :

MAMP/bin/php/php7.x.x/conf/php.ini

Default php.ini file :
Line 94: output_buffering = off

Change to :
output_buffering = 4096

Then stop and restart MAMP !

**Comment by nWidart** [comment]
Hello @aalssamani , this worked to make v3 work on asgardcms?

**Comment by aalssamani** [comment]
I have installed the latest Asgardcms

Beside,
There is another issue I faced NOT related to this one here.
The Fonts are busted due to CR - CR/LF conversion in git (possibly). So I copy the good fonts from one location to the others where they are damaged:
cp  ./Themes/Flatly/assets/fonts/fontawesome-webfont* ./public/themes/adminlte/vendor/font-awesome/fonts/
cp  ./Themes/Flatly/assets/fonts/fontawesome-webfont* ./Themes/Adminlte/assets/vendor/font-awesome/fonts/
cp ./Themes/Flatly/assets/fonts/fontawesome-webfont* ./public/fonts/vendor/font-awesome/
cp ./Themes/Flatly/assets/fonts/fontawesome-webfont* ./vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/font-awesome/fonts/
cp ./Themes/Flatly/assets/fonts/fontawesome-webfont* ./Themes/Flatly/fonts/vendor/font-awesome/
cp ./Themes/Flatly/assets/fonts/FontAwesome.otf ./public/themes/adminlte/vendor/font-awesome/fonts/
cp ./Themes/Flatly/assets/fonts/FontAwesome.otf ./Themes/Adminlte/assets/vendor/font-awesome/fonts/
cp ./Themes/Flatly/assets/fonts/FontAwesome.otf ./public/fonts/vendor/font-awesome/
cp ./Themes/Flatly/assets/fonts/FontAwesome.otf ./vendor/maximebf/debugbar/src/DebugBar/Resources/vendor/font-awesome/fonts/
cp ./Themes/Flatly/assets/fonts/FontAwesome.otf ./Themes/Flatly/fonts/vendor/font-awesome/

**Comment by chiragpipariya** [comment]
Hello 

try to remove space from below file at 1st line and try it , it's worked for me you can also try it.

/config/filesystems.php

**Comment by nWidart** [comment]
@chiragpipariya Nice catch!! I'll try this asap if this is indeed the root cause but it looks promising!

**Comment by nWidart** [comment]
I can confirm, this was indeed the cause! 

Thanks a lot @chiragpipariya 🎉

**Comment by chiragpipariya** [comment]
sure!! sure! why not. do it
