### ISSUE TITLE
Login/registration not working

### ISSUE THREAD

**Issue by silvio-gratani** [AsgardCms/Platform#581]
### Summary of issue
New project created with composer require, then installed with asgard:install: can't login with admin user.
Checking in db the admin user exists, but the login page keep reloading without error/warning notifications.
Trying to create new user: same behaviour, but no new record is create on users table.

### System Details

- Windows 10 Home 64bit
- PHP 7.1.16
- Laravel 5.5
- `AsgardCMS 3

**Comment by linhtinh92** [comment]
I got same issue here.

**Comment by Josue-IT** [comment]
Same issue. Please fix it...

**Comment by nWidart** [comment]
Feel free to contribute to free software.

**Comment by ChristianGiupponi** [comment]
I have found the problem, I will send a fix later tomorrow Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [AsgardCms/Platform] Login/registration not working (#581)Da: Nicolas Widart A: AsgardCms/Platform CC: Christian Giupponi ,Comment Feel free to contribute to free software.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AsgardCms/Platform","title":"AsgardCms/Platform","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AsgardCms/Platform"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nWidart in #581: Feel free to contribute to free software."}],"action":{"name":"View Issue","url":"https://github.com/AsgardCms/Platform/issues/581#issuecomment-418434876"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AsgardCms/Platform/issues/581#issuecomment-418434876",
"url": "https://github.com/AsgardCms/Platform/issues/581#issuecomment-418434876",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [AsgardCms/Platform] Login/registration not working (#581)",
"sections": [
{
"text": "",
"activityTitle": "**Nicolas Widart**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@nWidart",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"AsgardCms/Platform\",\n\"issueId\": 581,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"AsgardCms/Platform\",\n\"issueId\": 581\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/AsgardCms/Platform/issues/581#issuecomment-418434876"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 374732246\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by silvio-gratani** [comment]
thanks @ChristianGiupponi, i'll try your fix in the afternoon
