### ISSUE TITLE
Date format config and other l10n

### ISSUE THREAD

**Issue by Grummfy** [AsgardCms/Platform#63]
Hello,
I think it's a good idea to have from start a config file to defined some localization (l10n) things like date format.

**Comment by nWidart** [comment]
You're free to do so for you application. 

I'd like to keep AsgardCms as flexible as possible.
There's indeed a trick with carbon where you can set the format once, and every call to a date/datetime field will be that format while just using `$entity->created_at` instead of `$entity->created_at->format('d/m/Y')`.
You're free to use that if you like, or not. :smiley:
