### ISSUE TITLE
Module Scaffold

### ISSUE THREAD

**Issue by tanmuhittin** [AsgardCms/Platform#82]
Hi
I watched https://asgardcms.com/en/blog/posts/scaffold-your-module-with-the-scaffolder and it  seemed very practical. But I think there should be an option where we add fields to our entity. Like we want to create a Customers module where we want fields Name (varchar), Short Description (text), Logo (image) . In this way when we are done on console everything should be done. Panel must be running good and database must be migrated. Because What we do is always the same once we decided on fields. So why not to automate :) .

**Comment by nWidart** [comment]
Thanks for the suggestion.

Automation of fields was specifically left of because there to many custom options possible. You will not always want the usual text/varchar fields etc. 

I preferred leaving the field adding part off because of this. 
Maybe later on something like this could be added, but not in the near future, at least.
