### ISSUE TITLE
Asgard & Existing Applications

### ISSUE THREAD

**Issue by mvdstam** [AsgardCms/Platform#83]
Hi,

For me, and I hope a lot of people as well, AsgardCMS would be perfect as a drop-in solution to manage both existing (and new) applications through a backend. I want to be able to simply pull in Asgard through composer at any time during development. Right now, the only way to use AsgardCMS, is to start from scratch with a new `composer create-project asgardcms/platform` command.

I've come up with a solution that allows me to install AsgardCMS into an existing application, through the use of a [Symfony Console command](https://gist.github.com/mvdstam/52217f463a2b90c0d41d). The aforementioned example is a proof of concept and should be regarded as such. I find there were quite a bit of issues during installation of AsgardCMS in an existing application. At the moment, AsgardCMS seems quite intrusive and not modular at all. Let's fix that!

Through this issue, I hope to identify and (help to) solve of these problems. Here's what I encountered:

- The `pingpong/modules` package had to be installed seperately since it's still a seperate, forked package that isn't on packagist. If you try to install the specific `dev-feature/5.1` version immediately with the other dependencies, you'll get an error. Probably composer behaviour, but can easily be fixed by maintaining the forked version on packagist.
- All modules (8 modules + 2 themes) are actually necessary for the CMS to even work. This makes Asgard kind of heavy, especially if one simply wants a way to simply create a backend system for their existing webapplication.
- The `stylist` config file will result in an error when published out of the box, since AsgardCMS expects the `stylist::themes.paths` configuration setting to have a value.
-  For now, I've done a really, really, *really* stupid and dirty hack concerning the `app/Kernel.php` file (doesn't work well; again: this is a proof of concept) since Asgard __requires__ some Middleware to even work. This means that creating a backend for an API won't work unless there is some way to conditionally enable additional AsgardCMS-related middleware. And that means that there should be some (waterproof) way to determine whether or not a certain HTTP request was meant for the backend and not for the app. For example, my API is completely stateless and lightweight, but it would be very nice if I could manage some of the data or settings in a AsgardCMS-powered backend.
- The AdminLTE.css file (as well as some other assets) of the `AdminLTE` theme is pretty much hard-coded and pushed into git for the `asgardcms/platform` package. I'd highly recommend to manage the assets of modules and themes in a way that this isn't necessary. My package, [pixelindustries/modular-assets](https://github.com/Pixelindustries/modular-assets) can easily be expanded to run a simple `gulp` command within modules and themes, so all that remains is a simple `stylist:publish` to publish the compiled assets. My package already supports running `npm` and `bower` install commands; so all you'd need is your own raw less/scss files in addition to a `bower.json` file in git. Let's try to make the AsgardCMS modules as lightweight and portable as possible.
- Sentinel gave me some problems as well, since the out-of-the-box configuration file that ships with Sentinel doesn't use the `Modules\User\Entities\Sentinel\User` class for the `User` model right away. AsgardCMS, however, fully expects this. ~~AsgardCMS should use any existing `User` model and simply decorate it.~~ AsgardCMS should use it's own User model. Also see #86 for my view on the matter.
- AsgardCMS tries to fetch the (root) `composer.json` file to determine the version of the application. That is all fine and well, but AsgardCMS also uses Filesystem to do that, which means that the `filesystems` config file needs to point to the `base_path()` directory for the root, which is non-standard (and weird, since you usually store stuff in the `storage_path()` folder). In any case, why not simply fetch the `composer.json` file using `base_path() . '/composer.json`? Developers should never, ever, ever be forced to change such an important configuration setting for a third-party solution like Asgard. Instead, Asgard should be flexible and unobtrusive in this context.

In any case, let's try and make Asgard even more awesome! :smile:

**Comment by nWidart** [comment]
Hello and thanks for this very complete feedback!

First of all I'd like to say that Asgard was not intended to use outside of this base app. It's called modular, because you can enable & disable modules on the fly (without the core ones). This is what it can already do. 

1. "If you try to install the specific dev-feature/5.1 version immediately with the other dependencies, you'll get an error. " This shouldn't be the case. " but can easily be fixed by maintaining the forked version on packagist." Not as easy as it looks.
2. "All modules (8 modules + 2 themes) are actually necessary for the CMS to even work. " Again, this shouldn't be the case. The Core (required) modules are listed in one of the [Core module configuration files](https://github.com/AsgardCms/Platform/blob/develop/config/asgard.core.config.php#L9). The Menu module is still in there, but this is not required anymore. Previously this was called in a the Core service provider to prepare the front-end routes. This makes 5 required modules.
3. Seems logical since it needs to know where to look for themes. If I remember correctly you submitted a PR which sets the default to an empty array.
4. Concerning the middleware, Asgard does not have middleware in the kernel.php file. Not sure which ones you're referring to.
5. This is intended. So the new installations of asgard do not need to compile & publish assets, but rather can get started easily and quickly. Bower is already used.
6. Asgard does change the sentinel config file, but it does that at execution time.
7. If I remember correctly I use the Filesystem class and not Flysystem. The latter needs to app to be configured.

**Comment by mvdstam** [comment]
If Asgard isn't meant to be used outside of it's own platform, what's the use of a CMS? The way I understood it, is that Asgard provides a modular way to build a CMS backend. And still needing 5 modules just for the CMS to even function is, well, not really modular but just bloated to start with. What I hoped, is to be able to start off with just the Core module and just use the modules I want or need. Instead, I'm forced to use a Workshop module and an Menu module which just means unnecessary overhead.

Anyway. Asgard seemed to be an interesting drop-in solution to me to manage both new and existing applications, and it seemed logical as since it's modular and extensible. Asgard would be perfect to use to manage API's with a simple CRUD module, for example. But that should not mean that the API itself would be influenced by the backend in any way. The way you are describing Asgard, it that it's meant to be used as an full-fledged application itself instead of a CMS. That's perfectly fine of course, but that means Asgard really isn't what I'm looking for. :smile:

**Comment by nWidart** [comment]
I don't think we have the same definition of modular. :smile: 

> It's called modular, because you can enable & disable modules on the fly (without the core ones). This is what it can already do.

Do you know a lot of cms's that you can integrate with your existing app ? I know none.

**Comment by nWidart** [comment]
This being said, I'm absolutely not against making Asgard pluggable into existing sites. As long as it doesn't impact the main application.

This will also require the site that's going to be integrated with asgard to have some modifications applied on it to accept the asgard modules (as you saw).

**Comment by nWidart** [comment]
No more update on this, I'll close this issue for the time being.

I'm always available on slack/here to discuss this further.
